server:
  port: 8070

spring:
  profiles:
    active: local

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  data:
    rest:
      #https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.setting-repository-detection-strategy
      base-path: /api/v1
      return-body-on-create: true
      return-body-on-update: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/devti_kotlin?allowMultiQueries=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&passwordCharacterEncoding=UTF-8
    username: root
    password: password
  sql:
    init:
      mode: always


logging:
  level:
    root: INFO
    org.hibernate:
      SQL: DEBUG # to logger
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core:
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE